### ISSUE TITLE
Sudden OpenTeraPlus Crash

### ISSUE THREAD

**Issue by arsp2701** [introlab/openteraplus#16]
Machine : Windows 10 x64 AMD processor

Bug description:
OpenTeraPlus shuts down suddenly.

Steps taken until the bug arrived
1.	Started OpenTeraPlus, logged in with Admin account
2.	Started a new meeting with a participant (doesn't matter which)
3.	Start the meeting
4.	End the meeting and confirm the ending
5.	OpenTeraPlus Crash

The following file is the Qt application log.
[bug_2020-09-15.txt](https://github.com/introlab/openteraplus/files/5227107/bug_2020-09-15.txt)

**Comment by SBriere** [comment]
Thanks for the report!
This is a known issue: starting  / stopping a session isn't properly working yet in the application. This is related to #8, which is planned to be implemented and debugged in the next few days.

**Comment by SBriere** [comment]
Fixed in 4dc553c.
